name: Run Jest Tests

on:
  push:
    branches:
      - test104
      - abc
      - main/** # Matches any branches that are created from `main` or indirectly from `main`
      
  pull_request:
    branches:
      - main
      - main/** # Matches pull requests on branches created from `main`

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0] # Adjust based on your Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
